// react-frontend/src/components/SplitSecret.tsx
import { useMemo, useState, type FormEvent } from 'react'
import { splitSecret } from '../lib/api'
import { useVault } from '../hooks/useVault'

export function SplitSecret() {
  const vault = useVault()
  const [k, setK] = useState(3)
  const [n, setN] = useState(5)
  const [secret, setSecret] = useState('')
  const [touched, setTouched] = useState({ k: false, n: false, secret: false })
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [success, setSuccess] = useState<string | null>(null)

  const errors = useMemo(() => {
    const next = { k: '', n: '', secret: '' }
    if (!Number.isInteger(k) || k < 1) next.k = 'Threshold must be at least 1.'
    else if (k > 60) next.k = 'Threshold cannot exceed 60.'
    if (!Number.isInteger(n) || n < 1) next.n = 'Share count must be at least 1.'
    else if (n > 60) next.n = 'Share count cannot exceed 60.'
    else if (n < k) next.n = 'Share count (n) must be greater than or equal to threshold (k).'
    if (!secret.trim()) next.secret = 'Secret is required.'
    else if (secret.trim().length < 3) next.secret = 'Secret must be at least 3 characters.'
    else if (secret.length > 300) next.secret = 'Secret cannot exceed 300 characters.'
    return next
  }, [k, n, secret])

  const invalid = Boolean(errors.k || errors.n || errors.secret)

  async function onSubmit(event: FormEvent) {
    event.preventDefault()
    setTouched({ k: true, n: true, secret: true })
    setError(null)
    setSuccess(null)
    if (invalid) return

    setBusy(true)
    try {
      const shares = await splitSecret({ k, n, secret: secret.trim() })
      vault.replace(shares, k, n)
      setSuccess(`Created ${shares.length} signed shares. Any ${k} can reconstruct the secret.`)
      document.getElementById('vault')?.scrollIntoView({ behavior: 'smooth', block: 'start' })
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Split failed.')
    } finally {
      setBusy(false)
    }
  }

  return (
    <section className="panel" id="split" aria-labelledby="split-title">
      <div className="panel-intro">
        <p className="section-kicker">01 · Split</p>
        <h2 id="split-title">Fragment the secret</h2>
        <p>
          Choose a threshold <em>k</em> and total shares <em>n</em>. The API returns RSA-signed shares
          indexed from 1 to <em>n</em>.
        </p>
      </div>

      <form className="panel-body" noValidate onSubmit={onSubmit}>
        <div className="field-grid">
          <div className="field">
            <label htmlFor="threshold">Threshold (k)</label>
            <input
              id="threshold"
              type="number"
              inputMode="numeric"
              required
              value={k}
              onBlur={() => setTouched((t) => ({ ...t, k: true }))}
              onChange={(e) => setK(Number(e.target.value))}
            />
            {touched.k && errors.k ? (
              <p className="field-error" role="alert">
                {errors.k}
              </p>
            ) : null}
          </div>
          <div className="field">
            <label htmlFor="total-shares">Total shares (n)</label>
            <input
              id="total-shares"
              type="number"
              inputMode="numeric"
              required
              value={n}
              onBlur={() => setTouched((t) => ({ ...t, n: true }))}
              onChange={(e) => setN(Number(e.target.value))}
            />
            {touched.n && errors.n ? (
              <p className="field-error" role="alert">
                {errors.n}
              </p>
            ) : null}
          </div>
        </div>

        <div className="field">
          <label htmlFor="secret">Secret</label>
          <textarea
            id="secret"
            rows={4}
            placeholder="for-your-eyes-only"
            required
            value={secret}
            onBlur={() => setTouched((t) => ({ ...t, secret: true }))}
            onChange={(e) => setSecret(e.target.value)}
          />
          <div className="field-meta">
            <span>
              {secret.length} / 300
            </span>
            {touched.secret && errors.secret ? (
              <p className="field-error" role="alert">
                {errors.secret}
              </p>
            ) : null}
          </div>
        </div>

        {error ? (
          <p className="banner banner--error" role="alert">
            {error}
          </p>
        ) : null}
        {success ? (
          <p className="banner banner--ok" role="status">
            {success}
          </p>
        ) : null}

        <div className="actions">
          <button className="btn btn-primary" type="submit" disabled={busy || invalid}>
            {busy ? 'Splitting…' : 'Split secret'}
          </button>
        </div>
      </form>
    </section>
  )
}

// angular-frontend/src/app/features/split/split-secret.ts
import { Component, inject, signal } from '@angular/core';
import {
  FormField,
  form,
  max,
  maxLength,
  min,
  minLength,
  required,
  submit,
  validate,
} from '@angular/forms/signals';
import { firstValueFrom } from 'rxjs';
import { SecretSharingApiService } from '../../core/services/secret-sharing-api.service';
import { ShareVaultService } from '../../core/services/share-vault.service';

interface SplitModel {
  k: number | null;
  n: number | null;
  secret: string;
}

@Component({
  selector: 'ssf-split-secret',
  imports: [FormField],
  templateUrl: './split-secret.html',
  styleUrl: './split-secret.scss',
})
export class SplitSecret {
  private readonly api = inject(SecretSharingApiService);
  private readonly vault = inject(ShareVaultService);

  readonly busy = signal(false);
  readonly error = signal<string | null>(null);
  readonly successMessage = signal<string | null>(null);

  readonly model = signal<SplitModel>({
    k: 3,
    n: 5,
    secret: '',
  });

  readonly splitForm = form(this.model, (path) => {
    required(path.k, { message: 'Threshold is required.' });
    min(path.k, 1, { message: 'Threshold must be at least 1.' });
    max(path.k, 60, { message: 'Threshold cannot exceed 60.' });

    required(path.n, { message: 'Share count is required.' });
    min(path.n, 1, { message: 'Share count must be at least 1.' });
    max(path.n, 60, { message: 'Share count cannot exceed 60.' });

    required(path.secret, { message: 'Secret is required.' });
    minLength(path.secret, 3, { message: 'Secret must be at least 3 characters.' });
    maxLength(path.secret, 300, { message: 'Secret cannot exceed 300 characters.' });

    validate(path.secret, ({ value }) => {
      if (value().trim().length === 0) {
        return { kind: 'whitespace', message: 'Secret cannot be only whitespace.' };
      }
      return null;
    });

    validate(path.n, ({ value, valueOf }) => {
      const k = valueOf(path.k);
      const n = value();
      if (k != null && n != null && n < k) {
        return {
          kind: 'n-lt-k',
          message: 'Share count (n) must be greater than or equal to threshold (k).',
        };
      }
      return null;
    });
  });

  onSubmit(event: Event): void {
    event.preventDefault();
    this.error.set(null);
    this.successMessage.set(null);

    submit(this.splitForm, {
      action: async () => {
        const { k, n, secret } = this.model();
        if (k == null || n == null) {
          return;
        }

        this.busy.set(true);
        try {
          const shares = await firstValueFrom(
            this.api.splitSecret({ k, n, secret: secret.trim() }),
          );
          this.vault.replaceShares(shares, k, n);
          this.successMessage.set(
            `Created ${shares.length} signed shares. Any ${k} can reconstruct the secret.`,
          );
          document.getElementById('vault')?.scrollIntoView({ behavior: 'smooth', block: 'start' });
        } catch (err) {
          this.error.set(err instanceof Error ? err.message : 'Split failed.');
        } finally {
          this.busy.set(false);
        }
      },
    });
  }
}
